name: Deploy Frontend to Docker Hub and Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build frontend Docker image
      run: |
        docker build \
          --build-arg REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }} \
          -t emiruuzun/personel-faberk-frontend:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push frontend Docker image to Docker Hub
      run: |
        docker push emiruuzun/personel-faberk-frontend:latest

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
            cd /personel-faberk  # Doğru klasöre geçiş
            # Docker Compose işlemleri
            if [ -f docker-compose.yml ]; then
                echo "docker-compose.yml bulundu, işlemler başlatılıyor..."
                sudo docker compose down
                # Containerları güvenle kaldır
                for service in nginx frontend backend; do
                  if [ "$(sudo docker ps -a -q --filter "name=$service")" ]; then
                    sudo docker rm -f $(sudo docker ps -a -q --filter "name=$service") || true
                  else
                    echo "$service container bulunamadı, atlanıyor."
                  fi
                done
                # Görüntüleri kaldır (isteğe bağlı)
                if [ "$(sudo docker images -q)" ]; then
                  sudo docker rmi $(sudo docker images -q) || true
                fi
                # Docker Compose çalıştır
                sudo docker compose up -d --build
                echo "Docker Compose işlemleri başarıyla tamamlandı!"
            else
                echo "docker-compose.yml bulunamadı, işlem iptal edildi."
                exit 1
            fi
